trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Testing
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
          tox.env: 'py37'
        Python38:
          python.version: '3.8'
          tox.env: 'py38'
        Python39:
          python.version: '3.9'
          tox.env: 'py39'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
      displayName: 'Install dependencies'
    - script: tox -e $(tox.env)
      displayName: 'Run tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
    - task: PublishCodeCoverageResults@1
      condition: eq(variables['tox.env'],'py37')
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

  - job: 'Linting'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
      displayName: 'Use Python 3.7'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
      displayName: 'Install dependencies'
    - script: tox -e mypy
      displayName: 'Test typing'
    - script: tox -e lint
      displayName: 'Test linting'
